replicaCount: 1

image:
  repository:
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name:

podSecurityContext: {}

securityContext: {}

service:
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
