---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          imagePullPolicy: Always
          image: 828162785311.dkr.ecr.eu-central-1.amazonaws.com/backend:latest
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh","-c","sleep 60" ]
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
            tcpSocket:
              port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
