---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          imagePullPolicy: Always
          image: 828162785311.dkr.ecr.eu-central-1.amazonaws.com/frontend:latest
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh","-c","sleep 60" ]
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
            httpGet:
              port: 80
              httpHeaders:
                - name: Content-Type
                  value: text/html


---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50