version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-node-browsers
    steps:
      - run: echo "dummy"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: gibberish
