jobs:
  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      deployment-name:
        description: |
          Name of a deployment
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: $AWS_REGION
          install-kubectl: true
      - run:
          name: Get latest image
          command: |
            sed -i -e 's/latest/<< pipeline.git.revision >>/g' << parameters.deployment-name >>-deployment.yaml
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: << parameters.deployment-name >>-deployment.yaml
          resource-name: deployment/<< parameters.deployment-name >>-deployment
orbs:
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.11.2
  aws-ecr: circleci/aws-ecr@6.15.3
version: 2.1
workflows:
  deployment:
    jobs:
      - aws-ecr/build-and-push-image:
          name: build-frontend-to-ecr
          path: frontend/
          repo: frontend
          tag: "<< pipeline.git.revision >>"
      - aws-ecr/build-and-push-image:
          name: build-backend-to-ecr
          path: backend/
          repo: backend
          tag: "<< pipeline.git.revision >>"
      - create-deployment:
          name: deploy-backend-manifests
          cluster-name: $CLUSTER_NAME
          deployment-name: backend
          requires:
            - build-backend-to-ecr
      - create-deployment:
          name: deploy-frontend-manifests
          cluster-name: $CLUSTER_NAME
          deployment-name: frontend
          requires:
            - build-frontend-to-ecr
