service: tcpcheck

provider:
  name: google
  stage: dev
  runtime: nodejs10
  region: us-central1
  project: playground-s-11-b8544b
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - src/**
    - .gitignore
    - .git/**
    - out/test.js

functions:
  api:
    handler: api
    events:
      - http: path
